### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yahooo-m** [VisualAIKHU/Missing-AVQA#1]
Hi, great job!
When will u release the code?

**Comment by 9yur1** [comment]
Hi, Thank you for your interests. The code will be released as soon as possible!

**Comment by asmit203** [comment]
any update ?

**Comment by 9yur1** [comment]
You can check the code now!

**Comment by asmit203** [comment]
@9yur1 No, please can you provide the preprocessing code too for ADNI
